// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:word_riders/secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseSecrets.webApiKey,
    appId: FirebaseSecrets.webAppId,
    messagingSenderId: FirebaseSecrets.messagingSenderId,
    projectId: FirebaseSecrets.projectId,
    authDomain: FirebaseSecrets.authDomain,
    storageBucket: FirebaseSecrets.storageBucket,
    measurementId: FirebaseSecrets.webMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseSecrets.androidApiKey,
    appId: FirebaseSecrets.androidAppId,
    messagingSenderId: FirebaseSecrets.messagingSenderId,
    projectId: FirebaseSecrets.projectId,
    storageBucket: FirebaseSecrets.storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseSecrets.iosApiKey,
    appId: FirebaseSecrets.iosAppId,
    messagingSenderId: FirebaseSecrets.messagingSenderId,
    projectId: FirebaseSecrets.projectId,
    storageBucket: FirebaseSecrets.storageBucket,
    iosBundleId: FirebaseSecrets.iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: FirebaseSecrets.iosApiKey,
    appId: FirebaseSecrets.iosAppId,
    messagingSenderId: FirebaseSecrets.messagingSenderId,
    projectId: FirebaseSecrets.projectId,
    storageBucket: FirebaseSecrets.storageBucket,
    iosBundleId: FirebaseSecrets.iosBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: FirebaseSecrets.windowsApiKey,
    appId: FirebaseSecrets.windowsAppId,
    messagingSenderId: FirebaseSecrets.messagingSenderId,
    projectId: FirebaseSecrets.projectId,
    authDomain: FirebaseSecrets.authDomain,
    storageBucket: FirebaseSecrets.storageBucket,
    measurementId: FirebaseSecrets.windowsMeasurementId,
  );
}
