name: Flutter CI

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  analyze_and_build:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Création du fichier secrets
        run: cp lib/secrets_sample.dart lib/secrets.dart

      - name: Installation des dépendances
        run: flutter pub get

      - name: Analyse du code (Linter)
        run: flutter analyze

      - name: Exécution des tests
        run: flutter test
